nelmio_api_doc:
    path: /api/docs
    controller: Nelmio\ApiDocBundle\Controller\SwaggerUiController
nelmio_api_doc_json:
    path: /api/docs.json
    controller: Nelmio\ApiDocBundle\Controller\SwaggerController
